{{ if and .Values.grafana.enabled .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-grafana
  labels:
    app.kubernetes.io/name: {{ include "buildbuddy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "buildbuddy.chart" . }}
  annotations:
    {{- if lt .Capabilities.KubeVersion.Minor "18" }}
    kubernetes.io/ingress.class: nginx
    {{- end }}
    kubernetes.io/ingress.provider: nginx
spec:
  {{- if ge .Capabilities.KubeVersion.Minor "18" }}
  ingressClassName: nginx
  {{- end }}
  rules:
    - host: {{ .Values.ingress.httpHost }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Release.Name }}-grafana
                port: 
                  number: 80
            path: /grafana/
            pathType: Prefix
{{ end }}
